
import Class_and_controller.TaiKhoan;
import Class_and_controller.CauLenh;
import com.microsoft.sqlserver.jdbc.SQLServerDataSource;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author thanh
 */
public class Dang_Ky extends javax.swing.JFrame {

    /**
     * Creates new form Dang_Nhap
     */
    
    String TaiKhoan;
    
    public Dang_Ky() {
        initComponents();
        setTitle("Phần mềm học Kanji");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnChuyenSangTrangDangNhap = new javax.swing.JButton();
        btnDangKy = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();
        txtGmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setText("Trang đăng ký");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 331, -1));

        txtTaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        getContentPane().add(txtTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 500, -1));

        txtMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        getContentPane().add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 500, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Tài khoản:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        btnChuyenSangTrangDangNhap.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnChuyenSangTrangDangNhap.setText("Đăng nhập");
        btnChuyenSangTrangDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenSangTrangDangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(btnChuyenSangTrangDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 210, 70));

        btnDangKy.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnDangKy.setText("Đăng ký");
        btnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 170, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Mật khẩu:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        txtTen.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        getContentPane().add(txtTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 500, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setText("Tên:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        btnBack1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnBack1.setText("Quay lại");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 590, 180, 70));

        txtGmail.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        getContentPane().add(txtGmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 500, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setText("Email:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChuyenSangTrangDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenSangTrangDangNhapActionPerformed
        this.setVisible(false);
        Dang_Nhap frm = new Dang_Nhap();
        frm.TaiKhoan = TaiKhoan;
        frm.setVisible(true);
    }//GEN-LAST:event_btnChuyenSangTrangDangNhapActionPerformed

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
        if (txtTaiKhoan.getText().equals("") || txtMatKhau.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Xin hãy điền đầy đủ thông tin");
        }
        else{
            CauLenh connect = new CauLenh();
            var conn = connect.conn;
            try{
                System.out.println("Ket noi thanh cong "+conn.getCatalog());
                var cauLenh = conn.prepareStatement("select * from TaiKhoan");
                var thucThi = cauLenh.executeQuery();
                List<TaiKhoan> list = new ArrayList();
                while(thucThi.next()){
                    TaiKhoan a = new TaiKhoan(thucThi.getString(1), thucThi.getString(2), thucThi.getString(3), thucThi.getString(4));
                    list.add(a);
                }
                var kt = true;
                for(TaiKhoan a : list){
                    if(a.getTaiKhoan().trim().equals(txtTaiKhoan.getText())){
                        JOptionPane.showMessageDialog(rootPane, "Đã tồn tại tài khoản này");
                        kt = false;
                        break;
                    }
                }
                if (kt == true){
                    String matKhau = connect.MaHoa(txtMatKhau.getText());
                    String lenh = "insert into TaiKhoan VALUES ('" + txtTaiKhoan.getText() + "','" + matKhau + "',N'" + txtTen.getText() + "',N'" + txtGmail.getText() + "')";
                    var Statement = conn.createStatement();
                    Statement.executeUpdate(lenh);

                    JOptionPane.showMessageDialog(rootPane, "Đăng ký thành công");
                    TaiKhoan = txtTaiKhoan.getText();

                    this.setVisible(false);
                    Trang_Chu frm = new Trang_Chu();
                    frm.TaiKhoan = TaiKhoan;
                    frm.setVisible(true);
                }
            }
            catch (SQLException ex) {
                ex.printStackTrace();
            }  
        }
    }//GEN-LAST:event_btnDangKyActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Trang_Chu frm = new Trang_Chu();
        frm.TaiKhoan = TaiKhoan;
        frm.setVisible(true);
    }//GEN-LAST:event_btnBack1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dang_Nhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dang_Nhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dang_Nhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dang_Nhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dang_Ky().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnChuyenSangTrangDangNhap;
    private javax.swing.JButton btnDangKy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtGmail;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtTaiKhoan;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
