
import Class_and_controller.TaiKhoan;
import Class_and_controller.CauLenh;
import com.microsoft.sqlserver.jdbc.SQLServerDataSource;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author thanh
 */
public class Dang_Nhap extends javax.swing.JFrame {

    public Dang_Nhap() {
        initComponents();
        setTitle("Phần mềm học Kanji");
    }
    
    String TaiKhoan;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnDangNhap = new javax.swing.JButton();
        btnChuyenSangTrangDangKy = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnQuenMatKhau = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Tài khoản:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 415, 210, 70));

        btnChuyenSangTrangDangKy.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnChuyenSangTrangDangKy.setText("Đăng ký");
        btnChuyenSangTrangDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenSangTrangDangKyActionPerformed(evt);
            }
        });
        getContentPane().add(btnChuyenSangTrangDangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 415, 170, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Mật khẩu:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setText("Trang đăng nhập");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 430, 78));

        txtTaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        getContentPane().add(txtTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 480, -1));

        txtMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        getContentPane().add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 480, -1));

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnBack.setText("Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 505, 180, 70));

        btnQuenMatKhau.setText("Quên mật khẩu");
        btnQuenMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuenMatKhauActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuenMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        if (txtTaiKhoan.getText().equals("") || txtMatKhau.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Xin hãy điền đầy đủ thông tin");
        }
        else{
            CauLenh connect = new CauLenh();
            var conn = connect.conn;
            try{
                System.out.println("Ket noi thanh cong "+conn.getCatalog());
                var cauLenh = conn.prepareStatement("select * from TaiKhoan");
                var thucThi = cauLenh.executeQuery();
                List<TaiKhoan> list = new ArrayList();
                while(thucThi.next()){
                    TaiKhoan a = new TaiKhoan(thucThi.getString(1), thucThi.getString(2), thucThi.getString(3), thucThi.getString(4));
                    list.add(a);
                }
                var kt = false;
                for(TaiKhoan a : list){
                    System.out.println(a.getTaiKhoan() + a.getMatKhau() + a.getTen());
                    String matKhau = connect.GiaiMa(a.getMatKhau().trim());
                    if(a.getTaiKhoan().trim().equals(txtTaiKhoan.getText()) && matKhau.equals(txtMatKhau.getText())){
                        kt = true;
                        JOptionPane.showMessageDialog(rootPane, "Đăng nhập thành công");

                        TaiKhoan = a.getTaiKhoan().trim();
                        this.setVisible(false);
                        Trang_Chu frm = new Trang_Chu();
                        frm.TaiKhoan = TaiKhoan;
                        frm.setVisible(true);
                        break;
                    }
                }
                if (kt == false){
                    JOptionPane.showMessageDialog(rootPane, "Sai tài khoản hoặc mật khẩu");
                }
            }
            catch (SQLException ex) {
                ex.printStackTrace();
            } 
        }
         
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void btnChuyenSangTrangDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenSangTrangDangKyActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Dang_Ky frm = new Dang_Ky();
        frm.TaiKhoan = TaiKhoan;
        frm.setVisible(true);
    }//GEN-LAST:event_btnChuyenSangTrangDangKyActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Trang_Chu frm = new Trang_Chu();
        frm.TaiKhoan = TaiKhoan;
        frm.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnQuenMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuenMatKhauActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Email frm = new Email();
        frm.TaiKhoan = txtTaiKhoan.getText();
        frm.setVisible(true);
    }//GEN-LAST:event_btnQuenMatKhauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dang_Nhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dang_Nhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dang_Nhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dang_Nhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dang_Nhap frm = new Dang_Nhap();
                frm.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChuyenSangTrangDangKy;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnQuenMatKhau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
