
import Class_and_controller.CauLenh;
import Class_and_controller.DiemSo;
import Class_and_controller.TaiKhoan;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author thanh
 */
public class Form_KetQua extends javax.swing.JFrame {

    /**
     * Creates new form Form_KetQua
     */
    public Form_KetQua() {
        initComponents();
        setTitle("Phần mềm học Kanji");
        countdonw();
    }
    
    Timer timer;
    int count;
    private void countdonw() {
        count = 1;
        timer = new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (count < 0) {
                    timer.stop();
                    label_KetQua.setText("Câu đúng/Tổng: " + diemSo + "/" + soCau);
                    label_TrinhDo.setText("Trình độ: N" + trinhDo);
                } else {
                    count--;
                }
            }
        });
        if (count != 0) {
            timer.start();
        }
    }
    
    String TaiKhoan;
    
    public Form_KetQua(int TrinhDo, int diemSo, int soCau) {
        initComponents();
        setTitle("Phần mềm học Kanji");
        this.diemSo = diemSo;
        this.soCau = soCau;
        trinhDo = TrinhDo;
        countdonw();
    }
        
    int diemSo;
    int soCau;
    int trinhDo;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_KetQua = new javax.swing.JLabel();
        btnTrangChu = new javax.swing.JButton();
        btnTiepTuc = new javax.swing.JButton();
        label_KetQua1 = new javax.swing.JLabel();
        label_TrinhDo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_KetQua.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        label_KetQua.setText("Câu đúng/Tổng:");
        getContentPane().add(label_KetQua, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        btnTrangChu.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnTrangChu.setText("Quay về trang chủ");
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });
        getContentPane().add(btnTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, 430, 80));

        btnTiepTuc.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnTiepTuc.setText("Tiếp tục");
        btnTiepTuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiepTucActionPerformed(evt);
            }
        });
        getContentPane().add(btnTiepTuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 210, 80));

        label_KetQua1.setFont(new java.awt.Font("Segoe UI", 1, 80)); // NOI18N
        label_KetQua1.setText("Kết quả");
        getContentPane().add(label_KetQua1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 300, -1));

        label_TrinhDo.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        label_TrinhDo.setText("Trình độ:");
        getContentPane().add(label_TrinhDo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    void luuVaoSQL(){
        if(TaiKhoan != null){
            CauLenh connect = new CauLenh();
            var conn = connect.conn;
            try{
                boolean kt = false;
                var cauLenh = conn.prepareStatement("select * from DiemSo where TaiKhoan = '" + TaiKhoan + "'");
                var thucThi = cauLenh.executeQuery();
                List<DiemSo> list = new ArrayList();
                while(thucThi.next()){
                    DiemSo a = new DiemSo(thucThi.getString(1), thucThi.getString(2), thucThi.getInt(3),thucThi.getInt(4));
                    list.add(a);
                }
                if (list == null){
                    String lenh = "insert into DiemSo VALUES ('" + TaiKhoan + "','N" + trinhDo + "'," + diemSo + "," + soCau + ")";
                    var Statement = conn.createStatement();
                    Statement.executeUpdate(lenh);
                }
                else{
                    for(DiemSo a : list){
                        if(a.getTrinhDo().trim().equals("N"+trinhDo)){
                            if(diemSo > a.getDiem()){
                                String lenh = "UPDATE DiemSo SET Diem = "+ diemSo +" WHERE TaiKhoan = '"+ TaiKhoan +"' and TrinhDo = 'N"+ trinhDo +"'";
                                var Statement = conn.createStatement();
                                Statement.executeUpdate(lenh);
                            }
                            kt = true;
                            break;
                        }
                    }
                    if(kt == false){
                        String lenh = "insert into DiemSo VALUES ('" + TaiKhoan + "','N" + trinhDo + "'," + diemSo + "," + soCau + ")";
                        var Statement = conn.createStatement();
                        Statement.executeUpdate(lenh);
                    }
                }
            }
            catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }
    
    private void btnTiepTucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiepTucActionPerformed
        // TODO add your handling code here:
        luuVaoSQL();
        this.setVisible(false);
        LuaChonDoKho frm = new LuaChonDoKho();
        frm.TaiKhoan = TaiKhoan;
        frm.setVisible(true);
    }//GEN-LAST:event_btnTiepTucActionPerformed

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChuActionPerformed
        // TODO add your handling code here:
        luuVaoSQL();
        this.setVisible(false);
        Trang_Chu frm = new Trang_Chu();
        frm.TaiKhoan = TaiKhoan;
        frm.setVisible(true);
    }//GEN-LAST:event_btnTrangChuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_KetQua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_KetQua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_KetQua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_KetQua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_KetQua().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTiepTuc;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JLabel label_KetQua;
    private javax.swing.JLabel label_KetQua1;
    private javax.swing.JLabel label_TrinhDo;
    // End of variables declaration//GEN-END:variables
}
