
import Class_and_controller.CauLenh;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Loc
 */
public class LuaChonDoKho extends javax.swing.JFrame {

    /**
     * Creates new form LuaChonDoKho
     */
    String TaiKhoan;
    
    public LuaChonDoKho() {
        initComponents();
        setTitle("Phần mềm học Kanji");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_N5 = new javax.swing.JButton();
        btn_N4 = new javax.swing.JButton();
        btn_N3 = new javax.swing.JButton();
        btn_N2 = new javax.swing.JButton();
        btn_N1 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 700));
        setPreferredSize(new java.awt.Dimension(800, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel1.setText("Lựa Chọn Cấp Độ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        btn_N5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn_N5.setText("N5");
        btn_N5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_N5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_N5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 360, 70));

        btn_N4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn_N4.setText("N4");
        btn_N4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_N4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_N4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 360, 70));

        btn_N3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn_N3.setText("N3");
        btn_N3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_N3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_N3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 360, 70));

        btn_N2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn_N2.setText("N2");
        btn_N2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_N2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_N2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 360, 70));

        btn_N1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn_N1.setText("N1");
        btn_N1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_N1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_N1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, 360, 70));

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnBack.setText("Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 670, 170, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_N4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_N4ActionPerformed
        this.setVisible(false);
        ChoiGame frm = new ChoiGame(4);
        frm.TaiKhoan = TaiKhoan;
        frm.setVisible(true);
    }//GEN-LAST:event_btn_N4ActionPerformed

    private void btn_N3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_N3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        NhapTu frm = new NhapTu(10);
        frm.list=new CauLenh().getListKanjiRadom(3);
        frm.TaiKhoan = TaiKhoan;
        frm.setVisible(true);
    }//GEN-LAST:event_btn_N3ActionPerformed

    private void btn_N2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_N2ActionPerformed
        this.setVisible(false);
        NhapTu frm = new NhapTu(15);
        frm.list=new CauLenh().getListKanjiRadom(2);
        frm.TaiKhoan = TaiKhoan;
        
        frm.setVisible(true);
    }//GEN-LAST:event_btn_N2ActionPerformed

    private void btn_N1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_N1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        NhapTu frm = new NhapTu(20);
        frm.list=new CauLenh().getListKanjiRadom(1);
        frm.TaiKhoan = TaiKhoan;
        frm.setVisible(true);
    }//GEN-LAST:event_btn_N1ActionPerformed

    private void btn_N5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_N5ActionPerformed
        this.setVisible(false);
        ChoiGame frm = new ChoiGame(5);
        frm.TaiKhoan = TaiKhoan;
        frm.setVisible(true);
    }//GEN-LAST:event_btn_N5ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Trang_Chu frm = new Trang_Chu();
        frm.TaiKhoan = TaiKhoan;
        frm.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LuaChonDoKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LuaChonDoKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LuaChonDoKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LuaChonDoKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LuaChonDoKho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btn_N1;
    private javax.swing.JButton btn_N2;
    private javax.swing.JButton btn_N3;
    private javax.swing.JButton btn_N4;
    private javax.swing.JButton btn_N5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
