/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import Class_and_controller.Kanji;
import Class_and_controller.CauLenh;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JCheckBox;
import javax.swing.JPanel;
import javax.swing.Timer;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.*;

/**
 *
 * @author ADMIN
 */
public class NhapTu extends javax.swing.JFrame {

    /**
     * Creates new form NhapTu1
     */
    
    String TaiKhoan;
    
    CauLenh connect = new CauLenh();
    public ArrayList<Kanji> list;
    private int a = 0;
    
    //Tổng số câu từ form LuaChonDoKho truyền qua theo N3 N....
    int limit; 
    int diem = 0;
    
    int count;
    int count1;
    
    int timeTuyThich = 15; //Nếu muốn thay đổi thời gian thì thay ở đây
    Timer timer;
    String duongDan = "src\\audio\\";
    
    

    public void setLimit(int limit) {
        this.limit = limit;
    }

    public NhapTu() {
        initComponents();
        setTitle("Phần mềm học Kanji");
        countdonw();
        //add(bang1());
    }

    public NhapTu(int limit) {
        initComponents();
        setTitle("Phần mềm học Kanji");
        this.limit = limit;
        countdonw();
        //add(bang1());
    }

    private void countdonw() {
        count = 3;

        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (count < 0) {
                    timer.stop();
                    jLabel1.setText(list.get(a).getKanji());
                    countdonwlimit();
                } else {
                    jLabel1.setText("" + count);
                    count--;
                }
            }
        });
        if (count != 0) {
            timer.start();
        }
    }
    
    void chuyenTrang(){
        this.setVisible(false);
        Form_KetQua frm = new Form_KetQua(3,diem,a);
        frm.TaiKhoan = TaiKhoan;
        frm.setVisible(true);
    }

    
    private void countdonwlimit() {
        count1 = timeTuyThich;

        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (a == limit) {
                    jLabel1.setText("Hoàn thành");
                    txtCauTraLoi.setText("");
                    timer.stop();
                    
                    //them form nao do sau khi  xong
                    //chuyenTrang();
                }
                if (count1 == 0) {
                    count1 = timeTuyThich;
                    a++;
                    jLabel1.setText(list.get(a).getKanji());
                    txtCauTraLoi.setText("");
                } else {
                    timer2.setText("" + count1);
                    count1--;
                }
            }
        });
        if (count1 != 0) {
            timer.start();
        }
    }

    private JPanel bang1() {
        setTitle("Orientation left to right");
        JPanel bang1 = new JPanel();
        bang1.setSize(58, 210);
        bang1.setBorder(BorderFactory.createBevelBorder(5));
        bang1.setBackground(Color.gray);
        bang1.setLocation(10, 30);

        for (int i = 0; i < limit; i++) {
            JCheckBox checkBox = new JCheckBox();
            checkBox.setText((i + 1) + "/" + limit);
            checkBox.setEnabled(false);

            checkBox.setForeground(Color.black);

            bang1.add(checkBox);
        }
        return bang1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCauTraLoi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnXacNhan = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        timer2 = new javax.swing.JLabel();
        ResultText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 102));
        setPreferredSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCauTraLoi.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        getContentPane().add(txtCauTraLoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 265, -1));

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 120)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 376, 193));

        btnXacNhan.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });
        getContentPane().add(btnXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 560, 180, 60));

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnBack.setText("Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 60));

        timer2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        getContentPane().add(timer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 80, 70));

        ResultText.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        getContentPane().add(ResultText, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 230, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    Player audio;
    
    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:

        if (list.get(a).getPhiemam().equals(txtCauTraLoi.getText())) {
            ResultText.setText("Chính xác");
            diem++;
            txtCauTraLoi.setText("");
        } else {
            ResultText.setText("Sai");
            txtCauTraLoi.setText("");
        }
        FileInputStream input;
        
        try {
            input = new FileInputStream(duongDan+list.get(a).getPhiemam()+".mp3");
            audio=new Player(input);
            audio.play();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NhapTu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JavaLayerException ex) {
            Logger.getLogger(NhapTu.class.getName()).log(Level.SEVERE, null, ex);
        }
        a++;
        count1 = timeTuyThich;
        
            
        
        jLabel1.setText(list.get(a).getKanji());
        if (a == limit) {
            jLabel1.setText("Hoàn thành");
            txtCauTraLoi.setText("");
            
            
            //them form nao do sau khi  xong
            chuyenTrang();
        }
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        LuaChonDoKho frm = new LuaChonDoKho();
        frm.TaiKhoan = TaiKhoan;
        frm.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhapTu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhapTu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhapTu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhapTu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NhapTu frm = new NhapTu();
                frm.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ResultText;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel timer2;
    private javax.swing.JTextField txtCauTraLoi;
    // End of variables declaration//GEN-END:variables

}
