
import Class_and_controller.CauLenh;
import Class_and_controller.DiemSo;
import Class_and_controller.TaiKhoan;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author thanh
 */
public class ThongTin_TaiKhoan extends javax.swing.JFrame {

    /**
     * Creates new form Form_KetQua
     */
    public ThongTin_TaiKhoan() {
        initComponents();
        setTitle("Phần mềm học Kanji");
        countdonw();
    }
    
    String TaiKhoan;
    
    Timer timer;
    int count;
    private void countdonw() {
        count = 1;
        timer = new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (count < 0) {
                    timer.stop();
                    boDuLieuVao();
                } else {
                    count--;
                }
            }
        });
        if (count != 0) {
            timer.start();
        }
    }
    
    void boDuLieuVao(){
        label_TaiKhoan.setText("Tài khoản: " + TaiKhoan);
        CauLenh connect = new CauLenh();
        var conn = connect.conn;
        try{
            var cauLenh = conn.prepareStatement("select * from DiemSo where TaiKhoan = '" + TaiKhoan + "'");
            var thucThi = cauLenh.executeQuery();
            List<DiemSo> list = new ArrayList();
            while(thucThi.next()){
                DiemSo a = new DiemSo(thucThi.getString(1), thucThi.getString(2), thucThi.getInt(3),thucThi.getInt(4));
                list.add(a);
            }
            for(DiemSo a : list){
                if(a.getTrinhDo().trim().equals("N5")){
                    label_N5.setText(a.getTrinhDo() + ": " + a.getDiem() + "/" + a.getSoCau());
                }
                else if(a.getTrinhDo().trim().equals("N4")){
                    label_N4.setText(a.getTrinhDo() + ": " + a.getDiem() + "/" + a.getSoCau());
                }
                else if(a.getTrinhDo().trim().equals("N3")){
                    label_N3.setText(a.getTrinhDo() + ": " + a.getDiem() + "/" + a.getSoCau());
                }
                else if(a.getTrinhDo().trim().equals("N2")){
                    label_N2.setText(a.getTrinhDo() + ": " + a.getDiem() + "/" + a.getSoCau());
                }
                else if(a.getTrinhDo().trim().equals("N1")){
                    label_N1.setText(a.getTrinhDo() + ": " + a.getDiem() + "/" + a.getSoCau());
                }
            }

            cauLenh = conn.prepareStatement("select * from TaiKhoan where TaiKhoan = '" + TaiKhoan + "'");
            thucThi = cauLenh.executeQuery();
            thucThi.next();
            label_Ten.setText("Tên: " + thucThi.getString("Ten"));
            label_Email.setText("Email: " + thucThi.getString("Email"));
        }
        catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTrangChu = new javax.swing.JButton();
        label_Email = new javax.swing.JLabel();
        label_N5 = new javax.swing.JLabel();
        label_TaiKhoan = new javax.swing.JLabel();
        label_N4 = new javax.swing.JLabel();
        label_N3 = new javax.swing.JLabel();
        label_N2 = new javax.swing.JLabel();
        label_N1 = new javax.swing.JLabel();
        label_ThongTin = new javax.swing.JLabel();
        label_Ten = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTrangChu.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnTrangChu.setText("Quay về trang chủ");
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });
        getContentPane().add(btnTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 750, 430, 80));

        label_Email.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        label_Email.setText("Email:");
        getContentPane().add(label_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        label_N5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        label_N5.setText("N5:");
        getContentPane().add(label_N5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        label_TaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        label_TaiKhoan.setText("Tài khoản:");
        getContentPane().add(label_TaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        label_N4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        label_N4.setText("N4:");
        getContentPane().add(label_N4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        label_N3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        label_N3.setText("N3:");
        getContentPane().add(label_N3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, -1, -1));

        label_N2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        label_N2.setText("N2:");
        getContentPane().add(label_N2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, -1, -1));

        label_N1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        label_N1.setText("N1:");
        getContentPane().add(label_N1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 650, -1, -1));

        label_ThongTin.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        label_ThongTin.setText("Thông tin tài khoản");
        getContentPane().add(label_ThongTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        label_Ten.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        label_Ten.setText("Tên:");
        getContentPane().add(label_Ten, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Trang_Chu frm = new Trang_Chu();
        frm.TaiKhoan = TaiKhoan;
        frm.setVisible(true);
    }//GEN-LAST:event_btnTrangChuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_KetQua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_KetQua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_KetQua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_KetQua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_KetQua().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JLabel label_Email;
    private javax.swing.JLabel label_N1;
    private javax.swing.JLabel label_N2;
    private javax.swing.JLabel label_N3;
    private javax.swing.JLabel label_N4;
    private javax.swing.JLabel label_N5;
    private javax.swing.JLabel label_TaiKhoan;
    private javax.swing.JLabel label_Ten;
    private javax.swing.JLabel label_ThongTin;
    // End of variables declaration//GEN-END:variables
}
