
import javax.swing.JFrame;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author thanh
 */
public class Trang_Chu extends javax.swing.JFrame {

    /**
     * Creates new form Trang_Chu
     */
    String TaiKhoan;
    
    public Trang_Chu() {
        initComponents();
        setTitle("Phần mềm học Kanji");
        countdonw();
    }
    
    Timer timer;
    int count;
    private void countdonw() {
        count = 1;
        timer = new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (count < 0) {
                    timer.stop();
                    if(TaiKhoan == null){
                        btnDangNhap.setVisible(true);
                        btnThongTin_TaiKhoan.setVisible(false);
                    }
                    else{
                        btnDangNhap.setVisible(false);
                        btnThongTin_TaiKhoan.setVisible(true);
                    }
                } else {
                    count--;
                }
            }
        });
        if (count != 0) {
            timer.start();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnChoi = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnDangNhap = new javax.swing.JButton();
        btnCredit = new javax.swing.JButton();
        btnDanhSach = new javax.swing.JButton();
        btnThongTin_TaiKhoan = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnChoi.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnChoi.setText("Bắt đầu");
        btnChoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoiActionPerformed(evt);
            }
        });
        getContentPane().add(btnChoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 310, 90));

        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 640, 310, 90));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel1.setText("Ứng dụng học Kanji");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 310, 90));

        btnCredit.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnCredit.setText("Credits");
        btnCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditActionPerformed(evt);
            }
        });
        getContentPane().add(btnCredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 520, 310, 90));

        btnDanhSach.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnDanhSach.setText("Danh sách");
        btnDanhSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhSachActionPerformed(evt);
            }
        });
        getContentPane().add(btnDanhSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 310, 90));

        btnThongTin_TaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnThongTin_TaiKhoan.setText("Tài khoản");
        btnThongTin_TaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongTin_TaiKhoanActionPerformed(evt);
            }
        });
        getContentPane().add(btnThongTin_TaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 310, 90));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/hinh.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-740, -10, 1700, 820));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoiActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        LuaChonDoKho frm = new LuaChonDoKho();
        frm.TaiKhoan = TaiKhoan;
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
    }//GEN-LAST:event_btnChoiActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Dang_Nhap frm = new Dang_Nhap();
        frm.TaiKhoan = TaiKhoan;
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void btnCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Trang_Gioi_Thieu_Nhom frm = new Trang_Gioi_Thieu_Nhom();
        frm.TaiKhoan = TaiKhoan;
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
    }//GEN-LAST:event_btnCreditActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnDanhSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhSachActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Trang_Hoc_Kanji frm = new Trang_Hoc_Kanji();
        frm.TaiKhoan = TaiKhoan;
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
    }//GEN-LAST:event_btnDanhSachActionPerformed

    private void btnThongTin_TaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongTin_TaiKhoanActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ThongTin_TaiKhoan frm = new ThongTin_TaiKhoan();
        frm.TaiKhoan = TaiKhoan;
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
    }//GEN-LAST:event_btnThongTin_TaiKhoanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trang_Chu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trang_Chu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trang_Chu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trang_Chu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        UIManager.setLookAndFeel("com.jtattoo.plaf.mint.MintLookAndFeel");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Trang_Chu frm = new Trang_Chu();
                frm.setLocationRelativeTo(null);
                frm.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton btnChoi;
    private javax.swing.JButton btnCredit;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnDanhSach;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnThongTin_TaiKhoan;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
