
import Class_and_controller.CauLenh;
import Class_and_controller.Kanji;
import Class_and_controller.TaiKhoan;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author thanh
 */
public class Trang_Hoc_Kanji extends javax.swing.JFrame {

    /**
     * Creates new form Trang_Hoc_Kanji
     */
    String TaiKhoan;
    
    CauLenh connect = new CauLenh();
    public  ArrayList<Kanji> list = connect.getListKanji();
    int trang = 1;
    
    public Trang_Hoc_Kanji() {
        initComponents();
        setTitle("Phần mềm học Kanji");
        if (trang == 1){  
            txtTrangHienTai.setText(String.valueOf(trang));
            
            txtSTT_1.setText(String.valueOf(list.get(0).getId()));
            txtKanji_1.setText(list.get(0).getKanji());
            txtPhienAm_1.setText(list.get(0).getPhiemam());
            txtHira_1.setText(list.get(0).getHiragana());
            txtMean_1.setText(list.get(0).getMean());

            txtSTT_2.setText(String.valueOf(list.get(1).getId()));
            txtKanji_2.setText(list.get(1).getKanji());
            txtPhienAm_2.setText(list.get(1).getPhiemam());
            txtHira_2.setText(list.get(1).getHiragana());
            txtMean_2.setText(list.get(1).getMean());
            
            txtSTT_3.setText(String.valueOf(list.get(2).getId()));
            txtKanji_3.setText(list.get(2).getKanji());
            txtPhienAm_3.setText(list.get(2).getPhiemam());
            txtHira_3.setText(list.get(2).getHiragana());
            txtMean_3.setText(list.get(2).getMean());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNext = new javax.swing.JButton();
        txtKanji_1 = new javax.swing.JLabel();
        txtPhienAm_1 = new javax.swing.JLabel();
        txtHira_1 = new javax.swing.JLabel();
        txtMean_1 = new javax.swing.JLabel();
        txtSTT_1 = new javax.swing.JLabel();
        txtKanji_2 = new javax.swing.JLabel();
        txtPhienAm_2 = new javax.swing.JLabel();
        txtHira_2 = new javax.swing.JLabel();
        txtMean_2 = new javax.swing.JLabel();
        txtSTT_2 = new javax.swing.JLabel();
        txtKanji_3 = new javax.swing.JLabel();
        txtPhienAm_3 = new javax.swing.JLabel();
        txtHira_3 = new javax.swing.JLabel();
        txtMean_3 = new javax.swing.JLabel();
        txtSTT_3 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtTrang = new javax.swing.JTextField();
        btnDiDenTrang = new javax.swing.JButton();
        txtTrangHienTai = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setPreferredSize(new java.awt.Dimension(1000, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNext.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnNext.setText("Tiếp theo");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 551, 230, 80));

        txtKanji_1.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        txtKanji_1.setText("1");
        getContentPane().add(txtKanji_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        txtPhienAm_1.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        txtPhienAm_1.setText("1");
        getContentPane().add(txtPhienAm_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        txtHira_1.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        txtHira_1.setText("1");
        getContentPane().add(txtHira_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, -1, -1));

        txtMean_1.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        txtMean_1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtMean_1.setText("1");
        getContentPane().add(txtMean_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        txtSTT_1.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        txtSTT_1.setText("1");
        getContentPane().add(txtSTT_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        txtKanji_2.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        txtKanji_2.setText("2");
        getContentPane().add(txtKanji_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        txtPhienAm_2.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        txtPhienAm_2.setText("2");
        getContentPane().add(txtPhienAm_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        txtHira_2.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        txtHira_2.setText("2");
        getContentPane().add(txtHira_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, -1, -1));

        txtMean_2.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        txtMean_2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtMean_2.setText("2");
        getContentPane().add(txtMean_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, -1, -1));

        txtSTT_2.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        txtSTT_2.setText("2");
        getContentPane().add(txtSTT_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        txtKanji_3.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        txtKanji_3.setText("3");
        getContentPane().add(txtKanji_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, -1));

        txtPhienAm_3.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        txtPhienAm_3.setText("3");
        getContentPane().add(txtPhienAm_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, -1, -1));

        txtHira_3.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        txtHira_3.setText("3");
        getContentPane().add(txtHira_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, -1, -1));

        txtMean_3.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        txtMean_3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtMean_3.setText("3");
        getContentPane().add(txtMean_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, -1, -1));

        txtSTT_3.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        txtSTT_3.setText("3");
        getContentPane().add(txtSTT_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnBack.setText("Lùi lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 551, 150, 80));

        txtTrang.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtTrang.setText("1");
        getContentPane().add(txtTrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, 60, 60));

        btnDiDenTrang.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnDiDenTrang.setText("Đi đến trang");
        btnDiDenTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiDenTrangActionPerformed(evt);
            }
        });
        getContentPane().add(btnDiDenTrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 660, 290, 80));

        txtTrangHienTai.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtTrangHienTai.setText("trang");
        getContentPane().add(txtTrangHienTai, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, -1, -1));

        btnBack1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnBack1.setText("Quay lại");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 180, 80));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        trang++;
        int tam = 0;
        for (int i = 1; i < trang; i++) {
            tam += 3;
        }
        if (tam + 2 > list.size()){
            JOptionPane.showMessageDialog(rootPane, "Đã đến trang cuối cùng");
            trang--;
        }
        else if (tam + 1 == list.size()){
            txtTrangHienTai.setText(String.valueOf(trang));
            
            txtSTT_1.setText(String.valueOf(list.get(tam).getId()));
            txtKanji_1.setText(list.get(tam).getKanji());
            txtPhienAm_1.setText(list.get(tam).getPhiemam());
            txtHira_1.setText(list.get(tam).getHiragana());
            txtMean_1.setText(list.get(tam).getMean());

            txtSTT_2.setText(String.valueOf(list.get(tam+1).getId()));
            txtKanji_2.setText(list.get(tam+1).getKanji());
            txtPhienAm_2.setText(list.get(tam+1).getPhiemam());
            txtHira_2.setText(list.get(tam+1).getHiragana());
            txtMean_2.setText(list.get(tam+1).getMean());
            
            txtSTT_3.setText("NULL");
            txtKanji_3.setText("NULL");
            txtPhienAm_3.setText("NULL");
            txtHira_3.setText("NULL");
            txtMean_3.setText("NULL");
        }
        else if (tam == list.size()){
            txtTrangHienTai.setText(String.valueOf(trang));
            
            txtSTT_1.setText(String.valueOf(list.get(tam).getId()));
            txtKanji_1.setText(list.get(tam).getKanji());
            txtPhienAm_1.setText(list.get(tam).getPhiemam());
            txtHira_1.setText(list.get(tam).getHiragana());
            txtMean_1.setText(list.get(tam).getMean());

            txtSTT_2.setText("NULL");
            txtKanji_2.setText("NULL");
            txtPhienAm_2.setText("NULL");
            txtHira_2.setText("NULL");
            txtMean_2.setText("NULL");
            
            txtSTT_3.setText("NULL");
            txtKanji_3.setText("NULL");
            txtPhienAm_3.setText("NULL");
            txtHira_3.setText("NULL");
            txtMean_3.setText("NULL");
        }
        else{
            txtTrangHienTai.setText(String.valueOf(trang));
            
            txtSTT_1.setText(String.valueOf(list.get(tam).getId()));
            txtKanji_1.setText(list.get(tam).getKanji());
            txtPhienAm_1.setText(list.get(tam).getPhiemam());
            txtHira_1.setText(list.get(tam).getHiragana());
            txtMean_1.setText(list.get(tam).getMean());

            txtSTT_2.setText(String.valueOf(list.get(tam+1).getId()));
            txtKanji_2.setText(list.get(tam+1).getKanji());
            txtPhienAm_2.setText(list.get(tam+1).getPhiemam());
            txtHira_2.setText(list.get(tam+1).getHiragana());
            txtMean_2.setText(list.get(tam+1).getMean());
            
            txtSTT_3.setText(String.valueOf(list.get(tam+2).getId()));
            txtKanji_3.setText(list.get(tam+2).getKanji());
            txtPhienAm_3.setText(list.get(tam+2).getPhiemam());
            txtHira_3.setText(list.get(tam+2).getHiragana());
            txtMean_3.setText(list.get(tam+2).getMean());
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        trang--;
        if (trang < 1){
            JOptionPane.showMessageDialog(rootPane, "Đã đến trang đầu tiên");
            trang++;
        }
        else{
            int tam = 0;
            for (int i = 1; i < trang; i++) {
                tam += 3;
            }
            txtTrangHienTai.setText(String.valueOf(trang));
            
            txtSTT_1.setText(String.valueOf(list.get(tam).getId()));
            txtKanji_1.setText(list.get(tam).getKanji());
            txtPhienAm_1.setText(list.get(tam).getPhiemam());
            txtHira_1.setText(list.get(tam).getHiragana());
            txtMean_1.setText(list.get(tam).getMean());

            txtSTT_2.setText(String.valueOf(list.get(tam+1).getId()));
            txtKanji_2.setText(list.get(tam+1).getKanji());
            txtPhienAm_2.setText(list.get(tam+1).getPhiemam());
            txtHira_2.setText(list.get(tam+1).getHiragana());
            txtMean_2.setText(list.get(tam+1).getMean());
            
            txtSTT_3.setText(String.valueOf(list.get(tam+2).getId()));
            txtKanji_3.setText(list.get(tam+2).getKanji());
            txtPhienAm_3.setText(list.get(tam+2).getPhiemam());
            txtHira_3.setText(list.get(tam+2).getHiragana());
            txtMean_3.setText(list.get(tam+2).getMean());
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDiDenTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiDenTrangActionPerformed
        // TODO add your handling code here:
        int tam = 0;
        for (int i = 1; i < Integer.parseInt(txtTrang.getText()); i++) {
            tam += 3;
        }
        if (tam + 2 > list.size()){
            JOptionPane.showMessageDialog(rootPane, "Không tồn tại trang");
        }
        else if (tam + 1 == list.size()){
            txtTrangHienTai.setText(String.valueOf(txtTrang.getText()));
            trang = Integer.parseInt(txtTrang.getText());
            
            txtSTT_1.setText(String.valueOf(list.get(tam).getId()));
            txtKanji_1.setText(list.get(tam).getKanji());
            txtPhienAm_1.setText(list.get(tam).getPhiemam());
            txtHira_1.setText(list.get(tam).getHiragana());
            txtMean_1.setText(list.get(tam).getMean());

            txtSTT_2.setText(String.valueOf(list.get(tam+1).getId()));
            txtKanji_2.setText(list.get(tam+1).getKanji());
            txtPhienAm_2.setText(list.get(tam+1).getPhiemam());
            txtHira_2.setText(list.get(tam+1).getHiragana());
            txtMean_2.setText(list.get(tam+1).getMean());
            
            txtSTT_3.setText("NULL");
            txtKanji_3.setText("NULL");
            txtPhienAm_3.setText("NULL");
            txtHira_3.setText("NULL");
            txtMean_3.setText("NULL");
        }
        else if (tam == list.size()){
            txtTrangHienTai.setText(String.valueOf(txtTrang.getText()));
            trang = Integer.parseInt(txtTrang.getText());
            
            txtSTT_1.setText(String.valueOf(list.get(tam).getId()));
            txtKanji_1.setText(list.get(tam).getKanji());
            txtPhienAm_1.setText(list.get(tam).getPhiemam());
            txtHira_1.setText(list.get(tam).getHiragana());
            txtMean_1.setText(list.get(tam).getMean());

            txtSTT_2.setText("NULL");
            txtKanji_2.setText("NULL");
            txtPhienAm_2.setText("NULL");
            txtHira_2.setText("NULL");
            txtMean_2.setText("NULL");
            
            txtSTT_3.setText("NULL");
            txtKanji_3.setText("NULL");
            txtPhienAm_3.setText("NULL");
            txtHira_3.setText("NULL");
            txtMean_3.setText("NULL");
        }
        else{
            txtTrangHienTai.setText(String.valueOf(txtTrang.getText()));
            trang = Integer.parseInt(txtTrang.getText());
            
            txtSTT_1.setText(String.valueOf(list.get(tam).getId()));
            txtKanji_1.setText(list.get(tam).getKanji());
            txtPhienAm_1.setText(list.get(tam).getPhiemam());
            txtHira_1.setText(list.get(tam).getHiragana());
            txtMean_1.setText(list.get(tam).getMean());

            txtSTT_2.setText(String.valueOf(list.get(tam+1).getId()));
            txtKanji_2.setText(list.get(tam+1).getKanji());
            txtPhienAm_2.setText(list.get(tam+1).getPhiemam());
            txtHira_2.setText(list.get(tam+1).getHiragana());
            txtMean_2.setText(list.get(tam+1).getMean());
            
            txtSTT_3.setText(String.valueOf(list.get(tam+2).getId()));
            txtKanji_3.setText(list.get(tam+2).getKanji());
            txtPhienAm_3.setText(list.get(tam+2).getPhiemam());
            txtHira_3.setText(list.get(tam+2).getHiragana());
            txtMean_3.setText(list.get(tam+2).getMean());
        }
    }//GEN-LAST:event_btnDiDenTrangActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Trang_Chu frm = new Trang_Chu();
        frm.TaiKhoan = TaiKhoan;
        frm.setVisible(true);
    }//GEN-LAST:event_btnBack1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trang_Hoc_Kanji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trang_Hoc_Kanji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trang_Hoc_Kanji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trang_Hoc_Kanji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trang_Hoc_Kanji().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnDiDenTrang;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel txtHira_1;
    private javax.swing.JLabel txtHira_2;
    private javax.swing.JLabel txtHira_3;
    private javax.swing.JLabel txtKanji_1;
    private javax.swing.JLabel txtKanji_2;
    private javax.swing.JLabel txtKanji_3;
    private javax.swing.JLabel txtMean_1;
    private javax.swing.JLabel txtMean_2;
    private javax.swing.JLabel txtMean_3;
    private javax.swing.JLabel txtPhienAm_1;
    private javax.swing.JLabel txtPhienAm_2;
    private javax.swing.JLabel txtPhienAm_3;
    private javax.swing.JLabel txtSTT_1;
    private javax.swing.JLabel txtSTT_2;
    private javax.swing.JLabel txtSTT_3;
    private javax.swing.JTextField txtTrang;
    private javax.swing.JLabel txtTrangHienTai;
    // End of variables declaration//GEN-END:variables
}
