
import Class_and_controller.CauLenh;
import Class_and_controller.DiemSo;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author thanh
 */
public class XacNhan_OTP extends javax.swing.JFrame {

    /**
     * Creates new form XacNhan_OTP
     */
    public XacNhan_OTP() {
        initComponents();
        setTitle("Khôi phục mật khẩu");
    }
    
    String TaiKhoan;
    String Email;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_OTP = new javax.swing.JTextField();
        btnXacNhan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_MatKhau = new javax.swing.JTextField();
        txt_MatKhauXacNhan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 300));
        setPreferredSize(new java.awt.Dimension(600, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Nhập OTP:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Mật khẩu mới:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        txt_OTP.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt_OTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_OTPActionPerformed(evt);
            }
        });
        getContentPane().add(txt_OTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 230, -1));

        btnXacNhan.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });
        getContentPane().add(btnXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 140, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Mật khẩu xác nhận:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        txt_MatKhau.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt_MatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MatKhauActionPerformed(evt);
            }
        });
        getContentPane().add(txt_MatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 230, -1));

        txt_MatKhauXacNhan.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt_MatKhauXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MatKhauXacNhanActionPerformed(evt);
            }
        });
        getContentPane().add(txt_MatKhauXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 230, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_OTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_OTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_OTPActionPerformed

    private void txt_MatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MatKhauActionPerformed

    private void txt_MatKhauXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MatKhauXacNhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MatKhauXacNhanActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
        CauLenh connect = new CauLenh();
        var conn = connect.conn;
        try{
            var cauLenh = conn.prepareStatement("select * from TaiKhoan where Email = N'" + Email + "'");
            var thucThi = cauLenh.executeQuery();
            thucThi.next();
            String tam = thucThi.getString("Otp");
            if (tam.contains(txt_OTP.getText())){
                if(txt_MatKhau.getText().equals("") || txt_MatKhauXacNhan.getText().equals("")){
                    JOptionPane.showMessageDialog(rootPane, "Không được để trống");
                }
                else if(txt_MatKhau.getText().equals(txt_MatKhauXacNhan.getText())){
                    String lenh = "UPDATE TaiKhoan SET MatKhau = N'" + txt_MatKhau.getText() + "' Where Email = N'" + Email + "'";
                    var Statement = conn.createStatement();
                    Statement.executeUpdate(lenh);
                    
                    JOptionPane.showMessageDialog(rootPane, "Đã đổi mật khẩu thành công");
                    this.setVisible(false);
                    Trang_Chu frm = new Trang_Chu();
                    frm.TaiKhoan = thucThi.getString("TaiKhoan");
                    frm.setVisible(true);
                }
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Sai OTP");
            }

        }
        catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnXacNhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XacNhan_OTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XacNhan_OTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XacNhan_OTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XacNhan_OTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XacNhan_OTP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txt_MatKhau;
    private javax.swing.JTextField txt_MatKhauXacNhan;
    private javax.swing.JTextField txt_OTP;
    // End of variables declaration//GEN-END:variables
}
